services:
#    app.example:
#        class: AppBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    app.project:
        class: AppBundle\Service\Impl\ProjectServiceImpl
        calls:
            - [setContainer, ['@service_container']]
    app.user_story:
        class: AppBundle\Service\Impl\UserStoryServiceImpl
        calls:
            - [setContainer, ['@service_container']]